name: Project Release
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release Type'
        required: true
        type: choice
        options:
          - Patch
          - Minor
          - Major

env:
  module: fs
jobs:
  Release:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/development'
    steps:
      - 
        name: Checkout
        uses: tiagomta/checkout@v1
        with:
          repository: vistta/vistta
          ref: ${{ github.ref }}
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0
          submodules: true
      - 
        name: ${{ inputs.type }} Release
        id: npm
        uses: tiagomta/npm@v1
        with:
          command: version ${{ inputs.type }} --email devops@vistta.org
          working-directory: ./packages/${{ env.module }}
      - 
        name: Create ${{ inputs.type }} Milestone
        id: milestone
        uses: tiagomta/gitea@v1
        with:
          command: milestone create "${{ inputs.type }} (v${{ steps.npm.outputs.result }})"
      - 
        name: Create PR (${{ inputs.type }})
        uses: tiagomta/gitea@v1
        with:
          command: pr create "${{ inputs.type }} (v${{ steps.npm.outputs.result }})" master development --milestone ${{ steps.milestone.outputs.result }} --labels "Project/Release ${{ inputs.type }}"
