name: Project Release
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release Type'
        required: true
        type: choice
        options:
          - Patch
          - Minor
          - Major

env:
  module: fs
  ref: refs/heads/development
jobs:
  Release:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master'
    steps:
      - 
        name: Checkout
        uses: tiagomta/checkout@v1
        with:
          ref: ${{ env.ref }}
          token: ${{ secrets.GIT_TOKEN }}
      - 
        name: Create PR
        uses: tiagomta/gitea@v1
        with:
          command: pr create "${{ inputs.type }}" ${{ github.ref }} ${{ env.ref }} --labels "Project/Release ${{ inputs.type }}"
