name: Project Release
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release Type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

env:
  module: fs
jobs:
  Release:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - 
        name: Checkout
        uses: tiagomta/checkout@v1
        with:
          repository: vistta/vistta
          ref: development
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0
          submodules: true
      - 
      - run: echo ${{ inputs.type }}